// <auto-generated />
using System;
using Dis1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dis1.Migrations
{
    [DbContext(typeof(Fara1Context))]
    [Migration("20190924180453_mail")]
    partial class mail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dis1.Models.Company", b =>
                {
                    b.Property<decimal>("Cc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(6, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAdress")
                        .HasColumnName("company_adress")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyDescription")
                        .HasColumnName("company_description")
                        .HasMaxLength(250);

                    b.Property<string>("CompanyInn")
                        .HasColumnName("Company_inn")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyLogin")
                        .IsRequired()
                        .HasColumnName("company_login")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnName("Company_name")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyPas")
                        .IsRequired()
                        .HasColumnName("company_pas")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyPhone")
                        .HasColumnName("company_phone")
                        .HasMaxLength(50);

                    b.Property<string>("Family")
                        .HasMaxLength(50);

                    b.Property<string>("Firstname")
                        .HasMaxLength(50);

                    b.Property<string>("Lasttname")
                        .HasColumnName("lasttname")
                        .HasMaxLength(50);

                    b.Property<string>("Mail");

                    b.HasKey("Cc");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Dis1.Models.Friends", b =>
                {
                    b.Property<decimal>("Cf")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cf")
                        .HasColumnType("numeric(6, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("FriendOne")
                        .HasColumnName("friend_one")
                        .HasColumnType("numeric(6, 0)");

                    b.Property<decimal?>("FriendTwo")
                        .HasColumnName("friend_two")
                        .HasColumnType("numeric(6, 0)");

                    b.Property<decimal>("Stat")
                        .HasColumnName("stat")
                        .HasColumnType("decimal(1, 0)");

                    b.HasKey("Cf");

                    b.HasIndex("FriendOne");

                    b.HasIndex("FriendTwo");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Dis1.Models.Report", b =>
                {
                    b.Property<decimal>("Cr")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cr")
                        .HasColumnType("numeric(6, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Cc")
                        .HasColumnName("cc")
                        .HasColumnType("numeric(6, 0)");

                    b.Property<string>("ReportCustomer")
                        .IsRequired()
                        .HasColumnName("report_customer")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ReportDate")
                        .HasColumnName("report_date")
                        .HasColumnType("date");

                    b.Property<string>("ReportName")
                        .HasColumnName("report_name")
                        .HasMaxLength(30);

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasColumnName("report_status")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("ReportWay")
                        .IsRequired()
                        .HasColumnName("report_way")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Cr");

                    b.HasIndex("Cc");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Dis1.Models.Shablon", b =>
                {
                    b.Property<decimal>("Cs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(6, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Cc")
                        .HasColumnName("cc")
                        .HasColumnType("numeric(6, 0)");

                    b.Property<string>("ShablonAgent")
                        .HasColumnName("shablon_agent")
                        .HasMaxLength(50);

                    b.Property<string>("ShablonName")
                        .IsRequired()
                        .HasColumnName("Shablon_name")
                        .HasMaxLength(50);

                    b.Property<string>("ShablonOrder")
                        .HasColumnName("shablon_order")
                        .HasMaxLength(50);

                    b.Property<string>("ShablonPosition")
                        .IsRequired()
                        .HasColumnName("Shablon_position")
                        .HasMaxLength(50);

                    b.HasKey("Cs");

                    b.HasIndex("Cc");

                    b.ToTable("Shablon");
                });

            modelBuilder.Entity("Dis1.Models.Friends", b =>
                {
                    b.HasOne("Dis1.Models.Company", "FriendOneNavigation")
                        .WithMany("FriendsFriendOneNavigation")
                        .HasForeignKey("FriendOne")
                        .HasConstraintName("FK__Friends__friend___36B12243");

                    b.HasOne("Dis1.Models.Company", "FriendTwoNavigation")
                        .WithMany("FriendsFriendTwoNavigation")
                        .HasForeignKey("FriendTwo")
                        .HasConstraintName("FK__Friends__friend___37A5467C");
                });

            modelBuilder.Entity("Dis1.Models.Report", b =>
                {
                    b.HasOne("Dis1.Models.Company", "CcNavigation")
                        .WithMany("Report")
                        .HasForeignKey("Cc")
                        .HasConstraintName("FK__Report__cc__2C3393D0");
                });

            modelBuilder.Entity("Dis1.Models.Shablon", b =>
                {
                    b.HasOne("Dis1.Models.Company", "CcNavigation")
                        .WithMany("Shablon")
                        .HasForeignKey("Cc")
                        .HasConstraintName("FK__Shablon__cc__29572725");
                });
#pragma warning restore 612, 618
        }
    }
}
